import{a as L,S as w,i as b}from"./assets/vendor-Qob_5Ba8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&e(d)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function e(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();const v="46858923-7c3fdcfc6a46f2062867c0871",$="https://pixabay.com/api/",E=15;async function y(r,o=1){const a=`${$}?key=${v}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${E}&page=${o}`;try{const e=await L.get(a);if(e.data.hits.length===0)throw new Error("No images found");return{images:e.data.hits,totalHits:e.data.totalHits}}catch(e){throw e}}let u;function m(r,o){const a=r.map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item">
        <div class="image-card">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          <div class="info">
            <p><strong>Likes:</strong> ${e.likes}</p>
            <p><strong>Views:</strong> ${e.views}</p>
            <p><strong>Comments:</strong> ${e.comments}</p>
            <p><strong>Downloads:</strong> ${e.downloads}</p>
          </div>
        </div>
      </a>`).join("");o.insertAdjacentHTML("beforeend",a),u?u.refresh():u=new w(".gallery-item",{captionsData:"alt",captionDelay:250})}function n(r){b.error({title:"Error",message:r,position:"topRight"})}function q(r){r.innerHTML=""}const S=document.querySelector("#search-form"),i=document.querySelector(".gallery"),g=document.querySelector("#loader"),l=document.querySelector("#load-more");let P="",c=1,f=0;S.addEventListener("submit",async r=>{r.preventDefault();const o=r.currentTarget.elements.searchQuery.value.trim();if(!o){n("Please enter a search term.");return}c=1,q(i),l.style.display="none",p();try{const{images:a,totalHits:e}=await y(o,c);f=e,m(a,i),f>15&&(l.style.display="block")}catch{n("Sorry, there are no images matching your search query. Please try again!")}finally{h()}});l.addEventListener("click",async()=>{c+=1,p();try{const{images:r}=await y(P,c);m(r,i),document.querySelectorAll(".gallery-item").length>=f&&(l.style.display="none",n("We're sorry, but you've reached the end of search results."));const{height:a}=i.firstElementChild.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}catch{n("Failed to load more images.")}finally{h()}});function p(){g.style.display="block"}function h(){g.style.display="none"}
//# sourceMappingURL=index.js.map
